[package]
name = "slam"
version = "0.1.0"
authors = ["jkopa <jarkopaczewski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.53"
sdl2 = "0.34"
